channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.9.1
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - packaging==23.2
  - pandas==2.1.3
  - protobuf==4.23.4
  - pyyaml==6.0.1
  - requests==2.31.0
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - tensorflow==2.15.0.post1
name: mlflow-env
